{{- range $app, $params := .Values.apps }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: {{ $app }}
  namespace: argocd
spec: 
  destination: 
    namespace: {{ $params.namespace }}
    server: "https://kubernetes.default.svc"
  project: default
  sources:
  - repoURL: {{ $params.repository }}
    targetRevision: {{ $params.branch }}
    path: {{ $params.path }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---

{{- end }}
